# 1) String formatter

In [ ]:
name = 'Vijay'

In [ ]:
# Using the .format() method
print('My name is {}'.format(name))

My name is Vijay

In [ ]:
# Using f-strings
print(f'My name is {name}')

My name is Vijay

# 2) Minimum widths and alignment between columns

In [ ]:
# create a list of tuples
marvel = [('Film', 'U.S. release date',	'Director(s)'),
          ('Iron Man',	'May 2, 2008', 'Jon Favreau'),
          ('The Incredible Hulk', 'June 13, 2008', 'Louis Leterrier'),
          ('Thor', 'May 6, 2011', 'Kenneth Branagh'),
          ('Captain America: The First Avenger', 'July 22, 2011',	'Joe Johnston'),]

In [ ]:
for film in marvel:
  print(film)
# It is not formatted properly

('Film', 'U.S. release date', 'Director(s)')
('Iron Man', 'May 2, 2008', 'Jon Favreau')
('The Incredible Hulk', 'June 13, 2008', 'Louis Leterrier')
('Thor', 'May 6, 2011', 'Kenneth Branagh')
('Captain America: The First Avenger', 'July 22, 2011', 'Joe Johnston')

In [ ]:
# enter variable space to align properly
for film in marvel:
  print(f'{film[0]:{40}}, {film[1]:{20}}, {film[2]:{10}}')

Film                                    , U.S. release date   , Director(s)
Iron Man                                , May 2, 2008         , Jon Favreau
The Incredible Hulk                     , June 13, 2008       , Louis Leterrier
Thor                                    , May 6, 2011         , Kenneth Branagh
Captain America: The First Avenger      , July 22, 2011       , Joe Johnston

In [ ]:
 # indicater between lines

# <   left align
# >   right align
# ^   centre align

for film in marvel:
  print(f'{film[0]:<{40}}, {film[1]:<{20}}, {film[2]:>{20}}')

Film                                    , U.S. release date   ,          Director(s)
Iron Man                                , May 2, 2008         ,          Jon Favreau
The Incredible Hulk                     , June 13, 2008       ,      Louis Leterrier
Thor                                    , May 6, 2011         ,      Kenneth Branagh
Captain America: The First Avenger      , July 22, 2011       ,         Joe Johnston

In [ ]:
# .  dot

for film in marvel:
  print(f'{film[0]:^{40}}, {film[1]:{20}}, {film[2]:.>{20}}')

                  Film                  , U.S. release date   , .........Director(s)
                Iron Man                , May 2, 2008         , .........Jon Favreau
          The Incredible Hulk           , June 13, 2008       , .....Louis Leterrier
                  Thor                  , May 6, 2011         , .....Kenneth Branagh
   Captain America: The First Avenger   , July 22, 2011       , ........Joe Johnston

# 3) Working with .csv and .tsv files

## Reading .tsv file

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/moviereviews.tsv',sep='\t')

In [ ]:
data.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [ ]:
# check the shape of data
data.shape
# 2000 rows and 2 columns

(2000, 2)

In [ ]:
# check the value counts
data['label'].value_counts()

# returns unique values and their count

neg    1000
pos    1000
Name: label, dtype: int64

## Writing a .tsv file

In [ ]:
pos = data[data['label']=='pos']

In [ ]:
pos.describe

<bound method NDFrame.describe of      label                                             review
2      pos  this has been an extraordinary year for austra...
3      pos  according to hollywood movies made in last few...
11     pos  with stars like sigourney weaver ( " alien " t...
16     pos  i remember hearing about this film when it fir...
18     pos  garry shandling makes his long overdue starrin...
...    ...                                                ...
1995   pos  i like movies with albert brooks , and i reall...
1996   pos  it might surprise some to know that joel and e...
1997   pos  the verdict : spine-chilling drama from horror...
1998   pos  i want to correct what i wrote in a former ret...
1999   pos  a couple of months ago , when i first download...

[1000 rows x 2 columns]>

In [ ]:
pos.head()

   label                                             review
2    pos  this has been an extraordinary year for austra...
3    pos  according to hollywood movies made in last few...
11   pos  with stars like sigourney weaver ( " alien " t...
16   pos  i remember hearing about this film when it fir...
18   pos  garry shandling makes his long overdue starrin...

In [ ]:
pos.to_csv('pos',sep='\t') # file saved as 'pos'

In [ ]:
data1 = pd.read_csv('/content/pos',sep='\t')

In [ ]:
data1.head()
# extra column unnamed is added here,
# this is because we haven't ignored indexes here

   Unnamed: 0 label                                             review
0           2   pos  this has been an extraordinary year for austra...
1           3   pos  according to hollywood movies made in last few...
2          11   pos  with stars like sigourney weaver ( " alien " t...
3          16   pos  i remember hearing about this film when it fir...
4          18   pos  garry shandling makes his long overdue starrin...

In [ ]:
# ignore indexes
data1 = pd.read_csv('/content/pos',sep='\t',index_col=0)
data1.head()

   label                                             review
2    pos  this has been an extraordinary year for austra...
3    pos  according to hollywood movies made in last few...
11   pos  with stars like sigourney weaver ( " alien " t...
16   pos  i remember hearing about this film when it fir...
18   pos  garry shandling makes his long overdue starrin...

In [ ]:
# Built in commannd to write a file

%%writefile test1.txt
Hello, this is a test file.
First line.
Second line.

Writing test1.txt

In [ ]:
# double click on the file to see the content

In [ ]:
# append another line in .txt file
%%writefile -a test1.txt
Thanks for adding the third line

Appending to test1.txt

## Builtin command to read and write

In [ ]:
file = open('/content/test1.txt',mode='r')

In [ ]:
file

In [ ]:
file.read()

'Hello, this is a test file.\nFirst line.\nSecond line.Thanks for adding the third line'

In [ ]:
file.read()
# second time we are getting output as single quote
# this is because: after reading file first time, pointer is at the end

''

In [ ]:
# set pointer at the beginning of file again
file.seek(0)

0

In [ ]:
file.read()

'Hello, this is a test file.\nFirst line.\nSecond line.Thanks for adding the third line'

In [ ]:
file.seek(1)
# set pointer at index 1

1

In [ ]:
file.read()
# index 0 is not in output

'ello, this is a test file.\nFirst line.\nSecond line.Thanks for adding the third line'

In [ ]:
file.seek(0)

0

In [ ]:
# another way to read the file
file.readlines()
# all the lines in output at a time

['Hello, this is a test file.\n',
 'First line.\n',
 'Second line.Thanks for adding the third line']

In [ ]:
file.seek(0)

0

In [ ]:
file.readline()
# first line in output

'Hello, this is a test file.\n'

In [ ]:
file.readline()
# second line in output

'First line.\n'

In [ ]:
file.readline()
# third line in output

'Second line.Thanks for adding the third line'

In [ ]:
file.readline()
# pointer at the end of lines

''

In [ ]:
file.seek(0)

0

In [ ]:
# close the file
file.close()

In [ ]:
file.readlines()
# after closing the file, we can't perform operations

ValueError: ignored

In [ ]:
# another way to open a file
with open('/content/test1.txt') as file:
  text = file.readlines()
  print(text)

['Hello, this is a test file.\n', 'First line.\n', 'Second line.Thanks for adding the third line']

In [ ]:
file.readlines()
# file is closed but we can read using above method

ValueError: ignored

In [ ]:
for i in text:
  print(i)
# the space between the lines because of \n

Hello, this is a test file.

First line.

Second line.Thanks for adding the third line

In [ ]:
for i in text:
  print(i.strip())
# strip all the extra charactors like \n and space

Hello, this is a test file.
First line.
Second line.Thanks for adding the third line

In [ ]:
# print the line numbers
for i, j in enumerate(text):
  print(str(i) + ' ---> ' + j.strip())

0 ---> Hello, this is a test file.
1 ---> First line.
2 ---> Second line.Thanks for adding the third line

# 4) File writing

In [ ]:
file = open('test2.txt', mode='w')

In [ ]:
file

In [ ]:
file.write('We are worling with twxt files in python')
# no of charactors in output

40

In [ ]:
# if we open the file test2.txt, then there is no content in file
# we need to close this file to complete the write operation

In [ ]:
file.close()
# now we can see data in file

In [ ]:
# we can write and save text in one operation
with open('test3.txt', 'w') as file:
  file.write('This is the new text file\n')

In [ ]:
text

['Hello, this is a test file.\n',
 'First line.\n',
 'Second line.Thanks for adding the third line']

In [ ]:
# append in file
with open('test3.txt', 'a') as file:
  for temp in text:
    file.write(temp)